AI:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/AI/AI.yaml
  path: ./Rules/AI/AI.yaml
  group: AI
Apple-domain:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Apple-domain.yaml
  path: ./Rules/Apple-domain.yaml
  group: GAM
Apple-ipcidr:
  behavior: ipcidr
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Apple-ipcidr.yaml
  path: ./Rules/Apple-ipcidr.yaml
  group: GAM
Amazon:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Amazon.yaml
  path: ./Rules/Media/Amazon.yaml
  group: GAM
China-streaming:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/China-streaming.yaml
  path: ./Rules/Media/China-streaming.yaml
  group: China
China-streaming-ipcidr:
  behavior: ipcidr
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/China-streaming-ipcidr.yaml
  path: ./Rules/Media/China-streaming.yaml
  group: China
Claude-ai:
  behavior: domain 
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/AI/Claude-ai.yaml
  path: ./Rules/AI/Claude-ai.yaml
  group: AI
Coursera:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Learning/Coursera.yaml
  path: ./Rules/Learning/Coursera.yaml
  group: Scholar
Disney Plus: 
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Disney%20Plus.yaml
  path: ./Rules/Media/Disney_Plus.yaml
  group: Amusement
Emby:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Emby.yaml
  path: ./Rules/Media/Emby.yaml
  group: Amusement
Github:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Daily/Github.yaml
  path: ./Rules/Daily/Github.yaml
  group: Tech
Google:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Google.yaml
  path: ./Rules/Google-domain.yaml
  group: GAM
Google-ipcidr:
  behavior: ipcidr
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Google-ipcidr.yaml
  path: ./Rules/Google-ipcidr.yaml
  group: GAM
HamiVideo:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/HamiVideo.yaml
  path: ./Rules/Media/HamiVideo.yaml
  group: Amusement
HBO Max:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/HBO%20Max.yaml
  path: ./Rules/Media/HBO_Max.yaml
  group: Amusement
JD:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/China/JD.yaml
  path: ./Rules/China/JD.yaml
  group: DIRECT
Microsoft:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Microsoft.yaml
  path: ./Rules/Microsoft.yaml
  group: GAM
Netflix:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Netflix.yaml
  path: ./Rules/Media/Netflix.yaml
  group: Amusement
Netflix-ipcidr:
  behavior: ipcidr
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Netflix-ipcidr.yaml
  path: ./Rules/Media/Netflix-ipcidr.yaml
  group: Amusement
OpenAI:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/AI/OpenAI.yaml
  path: ./Rules/AI/OpenAI.yaml
  group: AI
PayPal:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/PayPal.yaml
  path: ./Rules/PayPal.yaml
  group: GAM
Scholar:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Learning/Scholar.yaml
  path: ./Rules/Learning/Scholar.yaml
  group: Scholar
Speedtest:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Speedtest.yaml
  path: ./Rules/Speedtest.yaml
  group: GAM
Spotify:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Spotify.yaml
  path: ./Rules/Media/Spotify.yaml
  group: Amusement
StarPlus:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/StarPlus.yaml
  path: ./Rules/Media/StarPlus.yaml
  group: Amusement
StarPlusLogin:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/StarPlusLogin.yaml
  path: ./Rules/Media/StarPlusLogin.yaml
  group: Amusement
Steam:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Steam.yaml
  path: ./Rules/Steam.yaml
  group: Download
Packages:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Download/packages.yaml
  path: ./Rules/Download/Packages.yaml
  group: Download
Tech:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Daily/Tech.yaml
  path: ./Rules/Daily/Tech.yaml
  group: Tech
Telegram-ipcidr:
  behavior: ipcidr
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Telegram-ipcidr.yaml
  path: ./Rules/Telegram-ipcidr.yaml
  group: Amusement
Telegram:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Telegram.yaml
  path: ./Rules/Telegram.yaml
  group: Amusement
Tiktok:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Tiktok.yaml
  path: ./Rules/Media/Tiktok.yaml
  group: Amusement
Twitter:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Twitter.yaml
  path: ./Rules/Media/Twitter.yaml
  group: Amusement
YouTube:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/YouTube.yaml
  path: ./Rules/Media/YouTube.yaml
  group: Amusement
YouTube Music:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/YouTube%20Music.yaml
  path: ./Rules/Media/YouTube_Music.yaml
  group: Amusement
Domestic:
  behavior: domain
  url: https://github.com/Riczzoe/Clash-Rule-Set/raw/main/Provider/Domestic.yaml
  path: ./Rules/Domestic.yaml
  group: DIRECT
Domestic-ipcidr:
  behavior: ipcidr
  url: https://github.com/Riczzoe/Clash-Rule-Set/raw/main/Provider/Domestic-ipcidr.yaml
  path: ./Rules/Domestic-ipcidr.yaml
  group: DIRECT
LAN:
  behavior: ipcidr
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/LAN.yaml
  path: ./Rules/LAN.yaml
  group: DIRECT
China-Websites:
  behavior: domain
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/China/China-Websites.yaml
  path: ./Rules/China/China-Websites.yaml
  group: DIRECT
reject:
  behavior: domain
  url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
  path: ./Rules/Reject.yaml
  group: Reject
