AI:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/AI/AI.yaml
  path: ./Rules/AI/AI.yaml
  group: AI
Apple:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Apple.yaml
  path: ./Rules/Apple.yaml
  group: Apple
Amazon:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Amazon.yaml
  path: ./Rules/Media/Amazon.yaml
  group: Amazon
bilibili:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Bilibili.yaml
  path: ./Rules/Media/Bilibili.yaml
  group: Bilibili
Claude-ai:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/AI/Claude-ai.yaml
  path: ./Rules/AI/Claude-ai.yaml
  group: AI
Coursera:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Learning/Coursera.yaml
  path: ./Rules/Learning/Coursera.yaml
  group: Coursera
Disney Plus:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Disney%20Plus.yaml
  path: ./Rules/Media/Disney_Plus.yaml
  group: Disney
Emby:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Emby.yaml
  path: ./Rules/Media/Emby.yaml
  group: Emby
Google:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Google.yaml
  path: ./Rules/Google.yaml
  group: Google
HamiVideo:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/HamiVideo.yaml
  path: ./Rules/Media/HamiVideo.yaml
  group: HamiVideo
HBO Max:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/HBO%20Max.yaml
  path: ./Rules/Media/HBO_Max.yaml
  group: HBOMAX
IQ:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/IQ.yaml
  path: ./Rules/Media/IQI.yaml
  group: China
IQIYI:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/IQIYI.yaml
  path: ./Rules/Media/IQYI.yaml
  group: China
JD:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/China/JD.yaml
  path: ./Rules/China/JD.yaml
  group: DIRECT
Letv:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Letv.yaml
  path: ./Rules/Media/Letv.yaml
  group: China
Microsoft:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Microsoft.yaml
  path: ./Rules/Microsoft.yaml
  group: Microsoft
Netease Music:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Netease%20Music.yaml
  path: ./Rules/Media/Netease_Music.yaml
  group: China
Netflix:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Netflix.yaml
  path: ./Rules/Media/Netflix.yaml
  group: Netflix
OpenAI:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/AI/OpenAI.yaml
  path: ./Rules/AI/OpenAI.yaml
  group: AI
PayPal:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/PayPal.yaml
  path: ./Rules/PayPal.yaml
  group: PayPal
Scholar:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Learning/Scholar.yaml
  path: ./Rules/Learning/Scholar.yaml
  group: Scholar
Speedtest:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Speedtest.yaml
  path: ./Rules/Speedtest.yaml
  group: Speedtest
Spotify:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Spotify.yaml
  path: ./Rules/Media/Spotify.yaml
  group: Spotify
StarPlus:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/StarPlus.yaml
  path: ./Rules/Media/StarPlus.yaml
  group: StarPlus
StarPlusLogin:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/StarPlusLogin.yaml
  path: ./Rules/Media/StarPlusLogin.yaml
  group: StarPlusLogin
Steam:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Steam.yaml
  path: ./Rules/Steam.yaml
  group: Steam
Telegram:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Telegram.yaml
  path: ./Rules/Telegram.yaml
  group: Telegram
Tencent Video:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Tencent%20Video.yaml
  path: ./Rules/Media/Tencent_Video.yaml
  group: China
Tiktok:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Tiktok.yaml
  path: ./Rules/Media/Tiktok.yaml
  group: Tiktok
Twitter:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/Twitter.yaml
  path: ./Rules/Media/Twitter.yaml
  group: Twitter
Wechat:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/China/Wechat.yaml
  path: ./Rules/China/Wechat.yaml
  group: DIRECT
WeTV:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/WeTV.yaml
  path: ./Rules/Media/WeTV.yaml
  group: China
YouTube:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/Media/YouTube.yaml
  path: ./Rules/Media/YouTube.yaml
  group: YouTube
YouTube Music:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/YouTube%20Music.yaml
  path: ./Rules/Media/YouTube_Music.yaml
  group: YouTube
Youku:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Youku.yaml
  path: ./Rules/Media/Youku.yaml
  group: China
  

Domestic:
  behavior: classical
  url: https://github.com/Riczzoe/Clash-Rule-Set/raw/main/Provider/Domestic.yaml
  path: ./Rules/Domestic.yaml
  group: DIRECT
LAN:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/LAN.yaml
  path: ./Rules/LAN.yaml
  group: DIRECT
China-Websites:
  behavior: classical
  url: https://raw.githubusercontent.com/Riczzoe/Clash-Rule-Set/main/Provider/China/China-Websites.yaml
  path: ./Rules/China/China-Websites.yaml
  group: DIRECT
reject:
  behavior: classical
  url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Reject.yaml
  path: ./Rules/Reject.yaml
  group: Reject